# SOPS Configuration for APIS
# ===========================
# This file configures SOPS (Secrets OPerationS) for encrypting secrets locally.
#
# SETUP INSTRUCTIONS:
# 1. Install SOPS: brew install sops (macOS) or see https://github.com/getsops/sops
# 2. Install age: brew install age (macOS) or see https://github.com/FiloSottile/age
# 3. Generate a key: age-keygen -o ~/.config/sops/age/keys.txt
# 4. Add your public key below under 'age' recipients
# 5. Encrypt: sops --encrypt secrets/secrets.dec.yaml > secrets/secrets.enc.yaml
# 6. Decrypt: sops --decrypt secrets/secrets.enc.yaml > secrets/secrets.dec.yaml
#
# FOR TEAMS: Add each team member's age public key to the 'age' list below.
#
# TO CONNECT TO EXTERNAL OPENBAO:
# Simply change OPENBAO_ADDR and OPENBAO_TOKEN in .env - no SOPS needed.
# SOPS is only for local development secrets that need to be shared/committed.

creation_rules:
  # Encrypt all YAML files in secrets/ directory
  - path_regex: secrets/.*\.yaml$
    age: >-
      age1ddsze7ed9ux78zgn2jnx066ugc6kzp23hvh6e0z2kxkrag2qsy9sja68hc
    # Multiple keys (one per line) allow multiple team members to decrypt
    #
    # Example with multiple recipients:
    # age: >-
    #   age1abc123...(developer 1)
    #   age1def456...(developer 2)
    #   age1ghi789...(CI/CD service)
