name: Build image and open infra PR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      APP_ID: hivewarden-saas
      AI_ACTOR_NAME: "Hivewarden-SAAS AI Agent"
      AI_ACTOR_EMAIL: "hivewarden-saas-ai-agent@ratetheplate.dev"
      REGISTRY_HOST: forgejo.ratetheplate.dev
      REGISTRY_IMAGE: forgejo.ratetheplate.dev/ssik-apps/hivewarden-saas
      IMAGE_TAG: "${{ github.sha }}"
      INFRA_REPO_CLONE_URL: "https://forgejo.ratetheplate.dev/ssik/infrastructure.git"
      INFRA_VALUES_FILE: "helm/hivewarden-saas/values.yaml"
      OPENBAO_ADDR_DEFAULT: "https://bao.ratetheplate.dev"
      OPENBAO_CI_SECRET_PATH: "secret/data/apps/hivewarden-saas/ci/forgejo"
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Resolve release credentials
        id: creds
        run: |
          set -eu

          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

          role_id="${{ secrets.OPENBAO_ROLE_ID }}"
          secret_id="${{ secrets.OPENBAO_SECRET_ID }}"
          openbao_addr="${{ secrets.OPENBAO_ADDR }}"
          openbao_skip_verify="${{ secrets.OPENBAO_SKIP_VERIFY }}"
          source_mode="forgejo-secrets"

          if [ -n "${role_id}" ] && [ -n "${secret_id}" ]; then
            if [ -z "${openbao_addr}" ]; then
              openbao_addr="${OPENBAO_ADDR_DEFAULT}"
            fi

            curl_flags="-fsS"
            if [ "${openbao_skip_verify}" = "true" ]; then
              curl_flags="-k -fsS"
            fi

            login_payload="$(printf '{"role_id":"%s","secret_id":"%s"}' "${role_id}" "${secret_id}")"
            login_json="$(curl ${curl_flags} -X POST \
              -H "Content-Type: application/json" \
              "${openbao_addr}/v1/auth/approle/login" \
              -d "${login_payload}")"

            openbao_token="$(printf '%s' "${login_json}" | jq -r '.auth.client_token // empty')"
            if [ -z "${openbao_token}" ]; then
              echo "Failed to authenticate to OpenBao via AppRole" >&2
              exit 1
            fi

            secret_json="$(curl ${curl_flags} \
              -H "X-Vault-Token: ${openbao_token}" \
              "${openbao_addr}/v1/${OPENBAO_CI_SECRET_PATH}")"

            registry_username="$(printf '%s' "${secret_json}" | jq -r '.data.data.REGISTRY_USERNAME // empty')"
            registry_password="$(printf '%s' "${secret_json}" | jq -r '.data.data.REGISTRY_PASSWORD // empty')"
            infra_git_token="$(printf '%s' "${secret_json}" | jq -r '.data.data.INFRA_GIT_TOKEN // empty')"
            source_mode="openbao"
          else
            registry_username="${{ secrets.REGISTRY_USERNAME }}"
            registry_password="${{ secrets.REGISTRY_PASSWORD }}"
            infra_git_token="${{ secrets.INFRA_GIT_TOKEN }}"
          fi

          if [ -z "${registry_username}" ] || [ -z "${registry_password}" ] || [ -z "${infra_git_token}" ]; then
            echo "Missing release credentials. Configure OpenBao AppRole secrets or direct Forgejo secrets." >&2
            exit 1
          fi

          echo "::add-mask::${registry_password}"
          echo "::add-mask::${infra_git_token}"
          {
            echo "REGISTRY_USERNAME=${registry_username}"
            echo "REGISTRY_PASSWORD=${registry_password}"
            echo "INFRA_GIT_TOKEN=${infra_git_token}"
          } >> "$GITHUB_ENV"
          echo "source_mode=${source_mode}" >> "$GITHUB_OUTPUT"

      - name: Login to Forgejo registry
        run: |
          echo "${REGISTRY_PASSWORD}" | docker login "$REGISTRY_HOST" -u "${REGISTRY_USERNAME}" --password-stdin

      - name: Build and push APIS server image
        run: |
          docker build \
            --build-arg VERSION="${IMAGE_TAG}" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}" \
            --label org.opencontainers.image.source="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
            -f apis-server/Dockerfile \
            -t "${REGISTRY_IMAGE}:${IMAGE_TAG}" \
            apis-server

          docker push "${REGISTRY_IMAGE}:${IMAGE_TAG}"

      - name: Resolve immutable image digest
        id: digest
        run: |
          set -eu
          repo_digest="$(docker inspect --format='{{index .RepoDigests 0}}' "${REGISTRY_IMAGE}:${IMAGE_TAG}" || true)"

          if [ -z "${repo_digest}" ]; then
            image_digest="$(docker buildx imagetools inspect "${REGISTRY_IMAGE}:${IMAGE_TAG}" --format '{{.Manifest.Digest}}' || true)"
            if [ -z "${image_digest}" ]; then
              echo "Unable to resolve image digest for ${REGISTRY_IMAGE}:${IMAGE_TAG}" >&2
              exit 1
            fi
            repo_digest="${REGISTRY_IMAGE}@${image_digest}"
          fi

          image_digest="${repo_digest#*@}"
          echo "repo_digest=${repo_digest}" >> "$GITHUB_OUTPUT"
          echo "image_digest=${image_digest}" >> "$GITHUB_OUTPUT"

      - name: Checkout SSIK infrastructure repo
        run: |
          git clone "https://oauth2:${INFRA_GIT_TOKEN}@forgejo.ratetheplate.dev/ssik/infrastructure.git" infra

      - name: Update image tag and digest in infra values
        env:
          IMAGE_DIGEST: "${{ steps.digest.outputs.image_digest }}"
        run: |
          set -eu
          values_file="infra/${INFRA_VALUES_FILE}"
          tmp_file="${values_file}.tmp"

          test -f "${values_file}"

          awk -v image_tag="${IMAGE_TAG}" -v image_digest="${IMAGE_DIGEST}" '
          BEGIN {
            in_image = 0
            seen_tag = 0
            seen_digest = 0
          }
          {
            if ($0 ~ /^image:[[:space:]]*$/) {
              in_image = 1
              print
              next
            }

            if (in_image == 1) {
              if ($0 ~ /^[^[:space:]]/) {
                if (seen_tag == 0) {
                  print "  tag: \"" image_tag "\""
                }
                if (seen_digest == 0) {
                  print "  digest: \"" image_digest "\""
                }
                in_image = 0
              } else if ($0 ~ /^[[:space:]]*tag:[[:space:]]*/) {
                print "  tag: \"" image_tag "\""
                seen_tag = 1
                next
              } else if ($0 ~ /^[[:space:]]*digest:[[:space:]]*/) {
                print "  digest: \"" image_digest "\""
                seen_digest = 1
                next
              } else if ($0 ~ /^[[:space:]]*pullPolicy:[[:space:]]*/) {
                print
                if (seen_digest == 0) {
                  print "  digest: \"" image_digest "\""
                  seen_digest = 1
                }
                next
              }
            }

            print
          }
          END {
            if (in_image == 1) {
              if (seen_tag == 0) {
                print "  tag: \"" image_tag "\""
              }
              if (seen_digest == 0) {
                print "  digest: \"" image_digest "\""
              }
            }
          }
          ' "${values_file}" > "${tmp_file}"

          mv "${tmp_file}" "${values_file}"

      - name: Commit and push infra branch
        id: infra_commit
        env:
          IMAGE_DIGEST: "${{ steps.digest.outputs.image_digest }}"
        run: |
          set -eu
          cd infra

          release_branch="release/${APP_ID}-${IMAGE_TAG}"
          git config user.email "${AI_ACTOR_EMAIL}"
          git config user.name "${AI_ACTOR_NAME}"
          git checkout -B "${release_branch}"

          git add "${INFRA_VALUES_FILE}"
          if git diff --cached --quiet; then
            echo "No infra values changes detected"
            exit 0
          fi

          git commit -m "release(${APP_ID}): ${IMAGE_TAG} (${IMAGE_DIGEST}) [${AI_ACTOR_NAME}]"
          git push origin "${release_branch}"

          echo "release_branch=${release_branch}" >> "$GITHUB_OUTPUT"

      - name: Open infrastructure pull request
        if: steps.infra_commit.outputs.release_branch != ''
        id: pr
        env:
          IMAGE_DIGEST: "${{ steps.digest.outputs.image_digest }}"
        run: |
          set -eu
          branch="${{ steps.infra_commit.outputs.release_branch }}"
          pr_body="Automated GitOps release for ${APP_ID}. Image: ${REGISTRY_IMAGE}@${IMAGE_DIGEST}. Commit: ${GITHUB_SHA}. Runtime contract: release-handoff.md"
          pr_payload="$(printf '{"title":"release(%s): %s","head":"%s","base":"main","body":"%s"}' "${APP_ID}" "${IMAGE_TAG}" "${branch}" "${pr_body}")"

          pr_response="$(curl -sS -X POST \
            -H "Authorization: token ${INFRA_GIT_TOKEN}" \
            -H "Content-Type: application/json" \
            "https://forgejo.ratetheplate.dev/api/v1/repos/ssik/infrastructure/pulls" \
            -d "${pr_payload}")"

          pr_url="$(printf '%s' "${pr_response}" | sed -n 's/.*"html_url":"\([^"]*\)".*/\1/p')"
          if [ -z "${pr_url}" ]; then
            echo "Failed to create pull request" >&2
            echo "${pr_response}" >&2
            exit 1
          fi

          echo "pr_url=${pr_url}" >> "$GITHUB_OUTPUT"

      - name: Write release summary
        run: |
          {
            echo "## Hivewarden-SAAS release"
            echo ""
            echo "- Credentials source: \`${{ steps.creds.outputs.source_mode }}\`"
            echo "- Commit: \`${GITHUB_SHA}\`"
            echo "- Image: \`${{ steps.digest.outputs.repo_digest }}\`"
            if [ -n "${{ steps.pr.outputs.pr_url }}" ]; then
              echo "- Infra PR: ${{ steps.pr.outputs.pr_url }}"
            else
              echo "- Infra PR: not created (no infra values change detected)"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
