/**
 * HTTP Server Tests.
 *
 * Tests all HTTP endpoints:
 * - GET /status (no auth required)
 * - POST /arm, POST /disarm (auth required)
 * - GET /config, POST /config (auth required)
 * - GET /stream (auth required)
 * - Error handling (404, 400, 401)
 */

#include "http_server.h"
#include "config_manager.h"
#include "deterrent_state.h"
#include "manual_capture.h"
#include "log.h"
#include "platform.h"
#include "camera.h"
#include "vision_runtime.h"
#include "qr_scanner.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <pthread.h>

#include "cJSON.h"
#include "event_logger.h"

static char g_last_exchange_url[CFG_MAX_URL_LEN] = {0};

// ============================================================================
// Stubs for event_logger (avoid pulling in sqlite3 dependency)
// ============================================================================

bool event_logger_is_initialized(void) { return false; }
int event_logger_get_status(storage_status_t *status) {
    (void)status;
    return -1;
}

size_t camera_copy_last_qr_frame(uint8_t *dst, size_t capacity,
                                 uint16_t *width, uint16_t *height) {
    (void)dst;
    (void)capacity;
    if (width) {
        *width = 0;
    }
    if (height) {
        *height = 0;
    }
    return 0;
}

void camera_set_qr_profile(camera_qr_profile_t profile) {
    (void)profile;
}

camera_qr_profile_t camera_get_qr_profile(void) {
    return CAMERA_QR_PROFILE_SCREEN_GLARE;
}

const char *camera_qr_profile_name(camera_qr_profile_t profile) {
    switch (profile) {
        case CAMERA_QR_PROFILE_SCREEN_GLARE:
            return "screen_glare";
        case CAMERA_QR_PROFILE_SCREEN_BALANCED:
            return "screen_balanced";
        case CAMERA_QR_PROFILE_SCREEN_BRIGHT:
            return "screen_bright";
        default:
            return "unknown";
    }
}

int server_comm_exchange_claim_token(const char *url, const char *claim_token,
                                     char *api_key_out, size_t out_size) {
    if (!url || !claim_token || !api_key_out || out_size == 0) {
        return -1;
    }
    snprintf(g_last_exchange_url, sizeof(g_last_exchange_url), "%s", url);
    if (strcmp(claim_token, "HWCVALIDTOKEN") != 0) {
        return -1;
    }
    snprintf(api_key_out, out_size, "%s", "apis_test_claimed_key");
    return 0;
}

// ============================================================================
// Test Framework
// ============================================================================

static int tests_passed = 0;
static int tests_failed = 0;

#define TEST_ASSERT(cond, msg) do { \
    if (cond) { \
        printf("  PASS: %s\n", msg); \
        tests_passed++; \
    } else { \
        printf("  FAIL: %s\n", msg); \
        tests_failed++; \
    } \
} while(0)

// ============================================================================
// Auth Token
// ============================================================================

// Token read from the file generated by http_server_init()
static char g_auth_token[64] = {0};

/**
 * Read the local auth token from the file created by init_local_auth_token().
 * Tries both dev and production paths.
 */
static int read_auth_token(void) {
    const char *paths[] = {
        "./data/apis/local_auth_token",
        "../data/apis/local_auth_token",
        "/data/apis/local_auth_token",
        NULL
    };

    for (int i = 0; paths[i]; i++) {
        FILE *fp = fopen(paths[i], "r");
        if (fp) {
            size_t n = fread(g_auth_token, 1, sizeof(g_auth_token) - 1, fp);
            fclose(fp);
            if (n > 0) {
                g_auth_token[n] = '\0';
                return 0;
            }
        }
    }

    fprintf(stderr, "WARNING: Could not read auth token file\n");
    return -1;
}

// ============================================================================
// HTTP Client Helper
// ============================================================================

typedef struct {
    int status_code;
    char body[8192];
    size_t body_len;
    char content_type[128];
} http_response_t;

/**
 * Send an HTTP request. If auth_token is non-NULL, adds Authorization header.
 */
static int http_request(uint16_t port, const char *method, const char *path,
                        const char *body, const char *auth_token,
                        http_response_t *response) {
    // Create socket
    int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) {
        perror("socket");
        return -1;
    }

    // Connect
    struct sockaddr_in addr = {
        .sin_family = AF_INET,
        .sin_port = htons(port),
    };
    inet_pton(AF_INET, "127.0.0.1", &addr.sin_addr);

    if (connect(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("connect");
        close(sock);
        return -1;
    }

    // Build auth header line (empty string if no token)
    char auth_header[128] = "";
    if (auth_token && strlen(auth_token) > 0) {
        snprintf(auth_header, sizeof(auth_header),
                 "Authorization: Bearer %s\r\n", auth_token);
    }

    // Build request
    char request[2048];
    int req_len;
    if (body && strlen(body) > 0) {
        req_len = snprintf(request, sizeof(request),
            "%s %s HTTP/1.1\r\n"
            "Host: localhost\r\n"
            "%s"
            "Content-Type: application/json\r\n"
            "Content-Length: %zu\r\n"
            "Connection: close\r\n"
            "\r\n"
            "%s",
            method, path, auth_header, strlen(body), body);
    } else {
        req_len = snprintf(request, sizeof(request),
            "%s %s HTTP/1.1\r\n"
            "Host: localhost\r\n"
            "%s"
            "Connection: close\r\n"
            "\r\n",
            method, path, auth_header);
    }

    // Send request
    if (send(sock, request, req_len, 0) < 0) {
        perror("send");
        close(sock);
        return -1;
    }

    // Receive response until the server closes the connection.
    char buffer[8192];
    size_t total_received = 0;
    while (total_received < sizeof(buffer) - 1) {
        ssize_t received = recv(sock, buffer + total_received,
                                sizeof(buffer) - 1 - total_received, 0);
        if (received < 0) {
            perror("recv");
            close(sock);
            return -1;
        }
        if (received == 0) {
            break;
        }
        total_received += (size_t)received;
    }
    close(sock);

    if (total_received == 0) {
        return -1;
    }
    buffer[total_received] = '\0';

    // Parse response
    memset(response, 0, sizeof(*response));

    // Parse status line
    if (sscanf(buffer, "HTTP/1.1 %d", &response->status_code) != 1) {
        return -1;
    }

    // Find Content-Type header
    const char *ct = strstr(buffer, "Content-Type:");
    if (ct) {
        ct += 13;
        while (*ct == ' ') ct++;
        const char *ct_end = strstr(ct, "\r\n");
        if (ct_end) {
            size_t ct_len = ct_end - ct;
            if (ct_len >= sizeof(response->content_type)) {
                ct_len = sizeof(response->content_type) - 1;
            }
            memcpy(response->content_type, ct, ct_len);
            response->content_type[ct_len] = '\0';
        }
    }

    // Find body
    const char *body_start = strstr(buffer, "\r\n\r\n");
    if (body_start) {
        body_start += 4;
        size_t body_len = total_received - (size_t)(body_start - buffer);
        if (body_len >= sizeof(response->body)) {
            body_len = sizeof(response->body) - 1;
        }
        memcpy(response->body, body_start, body_len);
        response->body[body_len] = '\0';
        response->body_len = body_len;
    }

    return 0;
}

// ============================================================================
// Test: Status Endpoint (no auth required)
// ============================================================================

static void test_status_endpoint(uint16_t port) {
    printf("\n--- Test: Status Endpoint ---\n");

    http_response_t response;
    int result = http_request(port, "GET", "/status", NULL, NULL, &response);

    TEST_ASSERT(result == 0, "Request succeeded");
    TEST_ASSERT(response.status_code == 200, "Status code is 200");
    TEST_ASSERT(strstr(response.content_type, "application/json") != NULL, "Content-Type is JSON");

    // Parse JSON response
    cJSON *json = cJSON_Parse(response.body);
    TEST_ASSERT(json != NULL, "Response is valid JSON");

    if (json) {
        cJSON *armed = cJSON_GetObjectItem(json, "armed");
        TEST_ASSERT(armed != NULL && cJSON_IsBool(armed), "armed field is boolean");

        cJSON *detection = cJSON_GetObjectItem(json, "detection_enabled");
        TEST_ASSERT(detection != NULL && cJSON_IsBool(detection), "detection_enabled field is boolean");

        cJSON *uptime = cJSON_GetObjectItem(json, "uptime_seconds");
        TEST_ASSERT(uptime != NULL && cJSON_IsNumber(uptime), "uptime_seconds field is number");

        cJSON *detections = cJSON_GetObjectItem(json, "detections_today");
        TEST_ASSERT(detections != NULL && cJSON_IsNumber(detections), "detections_today field is number");

        cJSON *storage = cJSON_GetObjectItem(json, "storage_free_mb");
        TEST_ASSERT(storage != NULL && cJSON_IsNumber(storage), "storage_free_mb field is number");

        cJSON *version = cJSON_GetObjectItem(json, "firmware_version");
        TEST_ASSERT(version != NULL && cJSON_IsString(version), "firmware_version field is string");

        cJSON *home_source = cJSON_GetObjectItem(json, "home_source");
        TEST_ASSERT(home_source != NULL && cJSON_IsString(home_source), "home_source field is string");

        cJSON *install_profile = cJSON_GetObjectItem(json, "install_profile");
        TEST_ASSERT(install_profile != NULL && cJSON_IsString(install_profile),
                    "install_profile field is string");

        cJSON *qr = cJSON_GetObjectItem(json, "qr");
        TEST_ASSERT(qr != NULL && cJSON_IsObject(qr), "qr object is present");
        if (qr) {
            cJSON *active = cJSON_GetObjectItem(qr, "active");
            TEST_ASSERT(active != NULL && cJSON_IsBool(active),
                        "qr.active field is boolean");
            cJSON *last_code_count = cJSON_GetObjectItem(qr, "last_code_count");
            TEST_ASSERT(last_code_count != NULL && cJSON_IsNumber(last_code_count),
                        "qr.last_code_count field is number");
            cJSON *last_decode_error = cJSON_GetObjectItem(qr, "last_decode_error");
            TEST_ASSERT(last_decode_error != NULL && cJSON_IsString(last_decode_error),
                        "qr.last_decode_error field is string");
            cJSON *last_decode_pass = cJSON_GetObjectItem(qr, "last_decode_pass");
            TEST_ASSERT(last_decode_pass != NULL && cJSON_IsString(last_decode_pass),
                        "qr.last_decode_pass field is string");
            cJSON *operator_hint = cJSON_GetObjectItem(qr, "operator_hint");
            TEST_ASSERT(operator_hint != NULL && cJSON_IsString(operator_hint),
                        "qr.operator_hint field is string");
            cJSON *profile = cJSON_GetObjectItem(qr, "profile");
            TEST_ASSERT(profile != NULL && cJSON_IsString(profile),
                        "qr.profile field is string");
        }

        cJSON *claim = cJSON_GetObjectItem(json, "claim");
        TEST_ASSERT(claim != NULL && cJSON_IsObject(claim), "claim object is present");
        if (claim) {
            cJSON *available = cJSON_GetObjectItem(claim, "available");
            TEST_ASSERT(available != NULL && cJSON_IsBool(available),
                        "claim.available field is boolean");
            cJSON *pending = cJSON_GetObjectItem(claim, "pending_token");
            TEST_ASSERT(pending != NULL && cJSON_IsBool(pending),
                        "claim.pending_token field is boolean");
            cJSON *server_url = cJSON_GetObjectItem(claim, "server_url");
            TEST_ASSERT(server_url != NULL && cJSON_IsString(server_url),
                        "claim.server_url field is string");
        }

        cJSON *manual_capture = cJSON_GetObjectItem(json, "manual_capture");
        TEST_ASSERT(manual_capture != NULL && cJSON_IsObject(manual_capture),
                    "manual_capture object is present");
        if (manual_capture) {
            cJSON *state = cJSON_GetObjectItem(manual_capture, "state");
            TEST_ASSERT(state != NULL && cJSON_IsString(state),
                        "manual_capture.state field is string");

            cJSON *upload_state = cJSON_GetObjectItem(manual_capture, "upload_state");
            TEST_ASSERT(upload_state != NULL && cJSON_IsString(upload_state),
                        "manual_capture.upload_state field is string");
        }

        cJSON *deterrent = cJSON_GetObjectItem(json, "deterrent");
        TEST_ASSERT(deterrent != NULL && cJSON_IsObject(deterrent),
                    "deterrent object is present");
        if (deterrent) {
            cJSON *mode = cJSON_GetObjectItem(deterrent, "mode");
            TEST_ASSERT(mode != NULL && cJSON_IsString(mode),
                        "deterrent.mode field is string");

            cJSON *state = cJSON_GetObjectItem(deterrent, "state");
            TEST_ASSERT(state != NULL && cJSON_IsString(state),
                        "deterrent.state field is string");

            cJSON *would_move = cJSON_GetObjectItem(deterrent, "would_move");
            TEST_ASSERT(would_move != NULL && cJSON_IsBool(would_move),
                        "deterrent.would_move field is boolean");

            cJSON *annotated = cJSON_GetObjectItem(deterrent, "last_annotated_frame_path");
            TEST_ASSERT(annotated != NULL && cJSON_IsString(annotated),
                        "deterrent.last_annotated_frame_path field is string");
        }

        cJSON *vision = cJSON_GetObjectItem(json, "vision");
        TEST_ASSERT(vision != NULL && cJSON_IsObject(vision),
                    "vision object is present");
        if (vision) {
            cJSON *watch_mode_state = cJSON_GetObjectItem(vision, "watch_mode_state");
            TEST_ASSERT(watch_mode_state != NULL && cJSON_IsString(watch_mode_state),
                        "vision.watch_mode_state field is string");

            cJSON *sensor_mode = cJSON_GetObjectItem(vision, "sensor_mode");
            TEST_ASSERT(sensor_mode != NULL && cJSON_IsString(sensor_mode),
                        "vision.sensor_mode field is string");

            cJSON *lanes = cJSON_GetObjectItem(vision, "lanes");
            TEST_ASSERT(lanes != NULL && cJSON_IsArray(lanes),
                        "vision.lanes field is an array");
        }

        cJSON *business_sync = cJSON_GetObjectItem(json, "business_sync");
        TEST_ASSERT(business_sync != NULL && cJSON_IsObject(business_sync),
                    "business_sync object is present");
        if (business_sync) {
            cJSON *pending_entries = cJSON_GetObjectItem(business_sync, "pending_entries");
            TEST_ASSERT(pending_entries != NULL && cJSON_IsNumber(pending_entries),
                        "business_sync.pending_entries field is numeric");

            cJSON *last_status = cJSON_GetObjectItem(business_sync, "last_journal_sync_status");
            TEST_ASSERT(last_status != NULL && cJSON_IsString(last_status),
                        "business_sync.last_journal_sync_status field is string");

            cJSON *active_encounter = cJSON_GetObjectItem(business_sync, "active_encounter");
            TEST_ASSERT(active_encounter != NULL && cJSON_IsObject(active_encounter),
                        "business_sync.active_encounter object is present");
        }

        cJSON_Delete(json);
    }
}

// ============================================================================
// Test: Authentication
// ============================================================================

static void test_auth(uint16_t port) {
    printf("\n--- Test: Authentication ---\n");

    http_response_t response;

    // Request without auth token should get 401
    int result = http_request(port, "GET", "/config", NULL, NULL, &response);
    TEST_ASSERT(result == 0, "No-auth request succeeded");
    TEST_ASSERT(response.status_code == 401, "No-auth returns 401");

    // Request with wrong token should get 401
    result = http_request(port, "GET", "/config", NULL, "wrong_token", &response);
    TEST_ASSERT(result == 0, "Wrong-token request succeeded");
    TEST_ASSERT(response.status_code == 401, "Wrong token returns 401");

    // Request with correct token should get 200
    result = http_request(port, "GET", "/config", NULL, g_auth_token, &response);
    TEST_ASSERT(result == 0, "Auth request succeeded");
    TEST_ASSERT(response.status_code == 200, "Correct token returns 200");

    // /status should work without auth (public endpoint)
    result = http_request(port, "GET", "/status", NULL, NULL, &response);
    TEST_ASSERT(result == 0, "Status without auth succeeded");
    TEST_ASSERT(response.status_code == 200, "Status without auth returns 200");
}

// ============================================================================
// Test: Arm/Disarm Endpoints
// ============================================================================

static void test_arm_disarm_endpoints(uint16_t port) {
    printf("\n--- Test: Arm/Disarm Endpoints ---\n");

    http_response_t response;

    // Test POST /arm (with auth)
    int result = http_request(port, "POST", "/arm", NULL, g_auth_token, &response);
    TEST_ASSERT(result == 0, "Arm request succeeded");
    TEST_ASSERT(response.status_code == 200, "Arm status code is 200");

    cJSON *json = cJSON_Parse(response.body);
    if (json) {
        cJSON *armed = cJSON_GetObjectItem(json, "armed");
        TEST_ASSERT(armed != NULL && cJSON_IsTrue(armed), "Armed response shows true");
        cJSON_Delete(json);
    }

    // Verify armed state via status (no auth needed)
    result = http_request(port, "GET", "/status", NULL, NULL, &response);
    json = cJSON_Parse(response.body);
    if (json) {
        cJSON *armed = cJSON_GetObjectItem(json, "armed");
        TEST_ASSERT(armed != NULL && cJSON_IsTrue(armed), "Status shows armed=true");
        cJSON_Delete(json);
    }

    // Test POST /disarm (with auth)
    result = http_request(port, "POST", "/disarm", NULL, g_auth_token, &response);
    TEST_ASSERT(result == 0, "Disarm request succeeded");
    TEST_ASSERT(response.status_code == 200, "Disarm status code is 200");

    json = cJSON_Parse(response.body);
    if (json) {
        cJSON *armed = cJSON_GetObjectItem(json, "armed");
        TEST_ASSERT(armed != NULL && cJSON_IsFalse(armed), "Disarmed response shows false");
        cJSON_Delete(json);
    }

    // Verify disarmed state via status
    result = http_request(port, "GET", "/status", NULL, NULL, &response);
    json = cJSON_Parse(response.body);
    if (json) {
        cJSON *armed = cJSON_GetObjectItem(json, "armed");
        TEST_ASSERT(armed != NULL && cJSON_IsFalse(armed), "Status shows armed=false");
        cJSON_Delete(json);
    }

    // Test wrong method (with auth — should get 405, not 401)
    result = http_request(port, "GET", "/arm", NULL, g_auth_token, &response);
    TEST_ASSERT(result == 0 && response.status_code == 405, "GET /arm returns 405");
}

// ============================================================================
// Test: Config Endpoints
// ============================================================================

static void test_config_endpoints(uint16_t port) {
    printf("\n--- Test: Config Endpoints ---\n");

    http_response_t response;

    // Test GET /config (with auth)
    int result = http_request(port, "GET", "/config", NULL, g_auth_token, &response);
    TEST_ASSERT(result == 0, "Get config request succeeded");
    TEST_ASSERT(response.status_code == 200, "Get config status code is 200");

    cJSON *json = cJSON_Parse(response.body);
    TEST_ASSERT(json != NULL, "Config response is valid JSON");

    if (json) {
        // Check that API key is masked (should be "***" for non-empty keys, or empty if never set)
        cJSON *server = cJSON_GetObjectItem(json, "server");
        TEST_ASSERT(server != NULL, "Config has server section");
        if (server) {
            cJSON *api_key = cJSON_GetObjectItem(server, "api_key");
            if (api_key && cJSON_IsString(api_key)) {
                // If API key was set, it should be masked; if empty, that's also acceptable
                bool masked_or_empty = (strcmp(api_key->valuestring, "***") == 0 ||
                                       strlen(api_key->valuestring) == 0);
                TEST_ASSERT(masked_or_empty, "API key is masked or empty");
            }
        }
        cJSON *install_profile = cJSON_GetObjectItem(json, "install_profile");
        TEST_ASSERT(install_profile != NULL && cJSON_IsString(install_profile),
                    "Config has install_profile field");
        cJSON_Delete(json);
    }

    // Test POST /config with valid update (with auth)
    const char *update_json =
        "{\"detection\": {\"fps\": 15}, \"deterrent_mode\": \"live\", "
        "\"install_profile\": \"legacy\"}";
    result = http_request(port, "POST", "/config", update_json, g_auth_token, &response);
    TEST_ASSERT(result == 0, "Update config request succeeded");
    TEST_ASSERT(response.status_code == 200, "Update config status code is 200");

    // Verify FPS was updated
    result = http_request(port, "GET", "/config", NULL, g_auth_token, &response);
    json = cJSON_Parse(response.body);
    if (json) {
        cJSON *detection = cJSON_GetObjectItem(json, "detection");
        if (detection) {
            cJSON *fps = cJSON_GetObjectItem(detection, "fps");
            TEST_ASSERT(fps != NULL && fps->valueint == 15, "FPS was updated to 15");
        }

        cJSON *mode = cJSON_GetObjectItem(json, "deterrent_mode");
        TEST_ASSERT(mode != NULL && cJSON_IsString(mode) &&
                    strcmp(mode->valuestring, "live") == 0,
                    "Deterrent mode was updated to live");

        cJSON *install_profile = cJSON_GetObjectItem(json, "install_profile");
        TEST_ASSERT(install_profile != NULL && cJSON_IsString(install_profile) &&
                    strcmp(install_profile->valuestring, "legacy") == 0,
                    "Install profile was updated to legacy");
        cJSON_Delete(json);
    }

    // Test POST /config with invalid update (with auth)
    const char *invalid_json = "{\"detection\": {\"fps\": 100}}"; // Invalid: max is 30
    result = http_request(port, "POST", "/config", invalid_json, g_auth_token, &response);
    TEST_ASSERT(result == 0, "Invalid config request completed");
    TEST_ASSERT(response.status_code == 400, "Invalid config returns 400");

    json = cJSON_Parse(response.body);
    if (json) {
        cJSON *error = cJSON_GetObjectItem(json, "error");
        TEST_ASSERT(error != NULL && cJSON_IsString(error), "Error message present");
        cJSON_Delete(json);
    }

    // Test POST /config with empty body (with auth)
    result = http_request(port, "POST", "/config", "", g_auth_token, &response);
    TEST_ASSERT(result == 0 && response.status_code == 400, "Empty body returns 400");
}

static void test_manual_capture_state_machine(void) {
    printf("\n--- Test: Manual Capture State Machine ---\n");

    manual_capture_cleanup();
    manual_capture_init();

    manual_capture_snapshot_t snapshot;
    TEST_ASSERT(manual_capture_request(1, false, &snapshot) == 0,
                "Manual capture request succeeds");
    TEST_ASSERT(snapshot.state == MANUAL_CAPTURE_STATE_QUEUED,
                "Manual capture enters queued state");
    TEST_ASSERT(snapshot.duration_seconds == 2,
                "Manual capture duration is clamped to 2 seconds");
    TEST_ASSERT(snapshot.upload_state == MANUAL_CAPTURE_UPLOAD_SKIPPED,
                "Upload skipped is recorded immediately for upload=false");
    TEST_ASSERT(!snapshot.upload_requested,
                "Upload flag is preserved");

    TEST_ASSERT(manual_capture_request(3, true, NULL) == -1,
                "Second request is rejected while capture is queued");

    manual_capture_mark_recording("/data/clips/manual-1.avi", "2026-03-07T12:00:00Z");
    manual_capture_get_snapshot(&snapshot);
    TEST_ASSERT(snapshot.state == MANUAL_CAPTURE_STATE_RECORDING,
                "Manual capture enters recording state");

    clip_result_t result;
    memset(&result, 0, sizeof(result));
    snprintf(result.filepath, sizeof(result.filepath), "%s", "/data/clips/manual-1.avi");
    snprintf(result.recorded_at, sizeof(result.recorded_at), "%s", "2026-03-07T12:00:03Z");
    manual_capture_mark_recorded(&result);
    manual_capture_get_snapshot(&snapshot);
    TEST_ASSERT(snapshot.state == MANUAL_CAPTURE_STATE_RECORDED,
                "Manual capture enters recorded state");
    TEST_ASSERT(snapshot.upload_state == MANUAL_CAPTURE_UPLOAD_SKIPPED,
                "Upload state remains skipped for upload=false");

    TEST_ASSERT(manual_capture_request(3, true, &snapshot) == 0,
                "New manual capture request succeeds after previous one completed");
    TEST_ASSERT(snapshot.duration_seconds == 3,
                "Manual capture preserves 3 second duration");
    TEST_ASSERT(snapshot.upload_state == MANUAL_CAPTURE_UPLOAD_PENDING,
                "Upload requested starts in pending state");

    manual_capture_mark_recording("/data/clips/manual-2.avi", "2026-03-07T12:00:10Z");
    memset(&result, 0, sizeof(result));
    snprintf(result.filepath, sizeof(result.filepath), "%s", "/data/clips/manual-2.avi");
    snprintf(result.recorded_at, sizeof(result.recorded_at), "%s", "2026-03-07T12:00:13Z");
    manual_capture_mark_recorded(&result);
    manual_capture_mark_upload_queued();
    manual_capture_mark_upload_complete("/data/clips/manual-2.avi", UPLOAD_STATUS_SUCCESS);
    manual_capture_get_snapshot(&snapshot);
    TEST_ASSERT(snapshot.upload_state == MANUAL_CAPTURE_UPLOAD_UPLOADED,
                "Successful upload is reflected in manual capture state");

    manual_capture_cleanup();
    manual_capture_init();
}

static void test_capture_endpoint(uint16_t port) {
    printf("\n--- Test: Capture Endpoint ---\n");

    manual_capture_cleanup();
    manual_capture_init();

    http_response_t response;
    int result = http_request(port, "POST", "/capture",
                              "{\"duration_seconds\":3,\"upload\":true}",
                              g_auth_token, &response);
    TEST_ASSERT(result == 0, "Capture request succeeded");
    TEST_ASSERT(response.status_code == 202, "Capture request returns 202");

    cJSON *json = cJSON_Parse(response.body);
    TEST_ASSERT(json != NULL, "Capture response is valid JSON");
    if (json) {
        cJSON *request_id = cJSON_GetObjectItem(json, "request_id");
        TEST_ASSERT(request_id != NULL && cJSON_IsString(request_id) &&
                    strlen(request_id->valuestring) > 0,
                    "Capture response includes request_id");

        cJSON *state = cJSON_GetObjectItem(json, "state");
        TEST_ASSERT(state != NULL && cJSON_IsString(state) &&
                    strcmp(state->valuestring, "queued") == 0,
                    "Capture response state is queued");
        cJSON_Delete(json);
    }

    manual_capture_snapshot_t snapshot;
    manual_capture_get_snapshot(&snapshot);
    TEST_ASSERT(snapshot.state == MANUAL_CAPTURE_STATE_QUEUED,
                "Manual capture module received queued request");
    TEST_ASSERT(snapshot.upload_requested,
                "Capture endpoint preserves upload=true");

    result = http_request(port, "GET", "/status", NULL, NULL, &response);
    TEST_ASSERT(result == 0, "Status request after capture succeeded");
    json = cJSON_Parse(response.body);
    TEST_ASSERT(json != NULL, "Status after capture is valid JSON");
    if (json) {
        cJSON *manual_capture = cJSON_GetObjectItem(json, "manual_capture");
        cJSON *state = manual_capture ? cJSON_GetObjectItem(manual_capture, "state") : NULL;
        cJSON *upload_state = manual_capture ? cJSON_GetObjectItem(manual_capture, "upload_state") : NULL;

        TEST_ASSERT(state != NULL && cJSON_IsString(state) &&
                    strcmp(state->valuestring, "queued") == 0,
                    "Status exposes queued manual capture state");
        TEST_ASSERT(upload_state != NULL && cJSON_IsString(upload_state) &&
                    strcmp(upload_state->valuestring, "pending") == 0,
                    "Status exposes pending upload state");
        cJSON_Delete(json);
    }

    result = http_request(port, "POST", "/capture", NULL, g_auth_token, &response);
    TEST_ASSERT(result == 0, "Conflicting capture request completed");
    TEST_ASSERT(response.status_code == 409, "Second capture request returns 409");

    manual_capture_cleanup();
    manual_capture_init();
}

static void test_claim_endpoint(uint16_t port) {
    printf("\n--- Test: Claim Endpoint ---\n");

    qr_scanner_cleanup();
    qr_scanner_init_with_size(320, 240);
    config_manager_clear_api_key();
    http_response_t response;
    int result;

    config_manager_set_needs_setup(true);
    result = http_request(port, "GET", "/claim", NULL, NULL, &response);
    TEST_ASSERT(result == 0, "Claim page request during setup succeeded");
    TEST_ASSERT(response.status_code == 409,
                "Claim page is unavailable while captive setup is active");

    config_manager_set_needs_setup(false);
    config_manager_set_server("http://127.0.0.1:3000", NULL);

    result = http_request(port, "GET", "/claim", NULL, NULL, &response);
    TEST_ASSERT(result == 0, "Claim page request succeeded");
    TEST_ASSERT(response.status_code == 200, "Claim page returns 200 while unclaimed");
    TEST_ASSERT(strstr(response.content_type, "text/html") != NULL,
                "Claim page content type is HTML");

    result = http_request(port, "POST", "/claim",
                          "claim_token=HWCINVALIDTOKEN&server_url=http%3A%2F%2Fevil.example",
                          NULL, &response);
    TEST_ASSERT(result == 0, "Invalid claim submit completed");
    TEST_ASSERT(response.status_code == 400, "Invalid claim submit returns 400");

    runtime_config_t snapshot;
    config_manager_get_snapshot(&snapshot);
    TEST_ASSERT(strcmp(snapshot.server.url, "http://127.0.0.1:3000") == 0,
                "Failed claim does not poison persisted server URL");

    result = http_request(port, "POST", "/claim",
                          "claim_token=HWCVALIDTOKEN&server_url=http%3A%2F%2F127.0.0.1%3A3000",
                          NULL, &response);
    TEST_ASSERT(result == 0, "Claim submit succeeded");
    TEST_ASSERT(response.status_code == 200, "Claim submit returns 200");
    TEST_ASSERT(strstr(response.body, "Claim Complete") != NULL,
                "Claim success page is returned");

    config_manager_get_snapshot(&snapshot);
    TEST_ASSERT(strcmp(snapshot.server.api_key, "apis_test_claimed_key") == 0,
                "Claim submit persisted exchanged API key");
    TEST_ASSERT(strcmp(g_last_exchange_url, "http://127.0.0.1:3000") == 0,
                "Claim exchange uses the intended server URL");
    TEST_ASSERT(snapshot.needs_setup == false,
                "Claim submit leaves setup complete");
    TEST_ASSERT(!config_manager_has_pending_claim_token(),
                "Claim submit clears pending claim token");
    TEST_ASSERT(!config_manager_has_pending_claim_server_url(),
                "Claim submit clears pending claim server URL");

    qr_scanner_cleanup();
}

// ============================================================================
// Test: Stream Endpoint
// ============================================================================

static void test_stream_endpoint(uint16_t port) {
    printf("\n--- Test: Stream Endpoint ---\n");

    // Create socket and connect
    int sock = socket(AF_INET, SOCK_STREAM, 0);
    TEST_ASSERT(sock >= 0, "Socket created");

    struct sockaddr_in addr = {
        .sin_family = AF_INET,
        .sin_port = htons(port),
    };
    inet_pton(AF_INET, "127.0.0.1", &addr.sin_addr);

    int result = connect(sock, (struct sockaddr *)&addr, sizeof(addr));
    TEST_ASSERT(result == 0, "Connected to server");

    // Send request with auth
    char request[512];
    snprintf(request, sizeof(request),
        "GET /stream HTTP/1.1\r\n"
        "Host: localhost\r\n"
        "Authorization: Bearer %s\r\n"
        "Connection: close\r\n"
        "\r\n", g_auth_token);
    send(sock, request, strlen(request), 0);

    // Read response - may need multiple reads to get header + first frame
    char buffer[8192];
    size_t total_received = 0;

    // Set receive timeout
    struct timeval timeout = { .tv_sec = 2, .tv_usec = 0 };
    setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(timeout));

    // Read until we have enough data or timeout
    while (total_received < sizeof(buffer) - 1) {
        ssize_t received = recv(sock, buffer + total_received,
                                sizeof(buffer) - 1 - total_received, 0);
        if (received <= 0) break;
        total_received += received;

        // Check if we have a complete first frame
        buffer[total_received] = '\0';
        if (strstr(buffer, "--frame") && strstr(buffer, "image/jpeg")) {
            break; // Got what we need
        }
    }

    TEST_ASSERT(total_received > 0, "Received response");

    if (total_received > 0) {
        buffer[total_received] = '\0';

        // Check for MJPEG content type
        TEST_ASSERT(strstr(buffer, "multipart/x-mixed-replace") != NULL,
                    "Content-Type is multipart/x-mixed-replace");
        TEST_ASSERT(strstr(buffer, "boundary=frame") != NULL,
                    "Boundary marker present");

        // Check for first frame (may be in subsequent data)
        TEST_ASSERT(strstr(buffer, "--frame") != NULL,
                    "Frame boundary found");
        TEST_ASSERT(strstr(buffer, "image/jpeg") != NULL,
                    "JPEG content type in frame");
    }

    close(sock);
}

// ============================================================================
// Test: Error Handling
// ============================================================================

static void test_error_handling(uint16_t port) {
    printf("\n--- Test: Error Handling ---\n");

    http_response_t response;

    // Test 404 - Not Found (with auth, so we get 404 not 401)
    int result = http_request(port, "GET", "/nonexistent", NULL, g_auth_token, &response);
    TEST_ASSERT(result == 0, "404 request completed");
    TEST_ASSERT(response.status_code == 404, "Unknown endpoint returns 404");

    cJSON *json = cJSON_Parse(response.body);
    if (json) {
        cJSON *error = cJSON_GetObjectItem(json, "error");
        TEST_ASSERT(error != NULL && cJSON_IsString(error), "404 has error message");

        cJSON *code = cJSON_GetObjectItem(json, "code");
        TEST_ASSERT(code != NULL && code->valueint == 404, "404 has code field");
        cJSON_Delete(json);
    }

    // Test 405 - Method Not Allowed (status endpoint, no auth needed)
    result = http_request(port, "DELETE", "/status", NULL, NULL, &response);
    TEST_ASSERT(result == 0, "405 request completed");
    TEST_ASSERT(response.status_code == 405, "Wrong method returns 405");
}

// ============================================================================
// Test: Server Lifecycle
// ============================================================================

static void test_server_lifecycle(void) {
    printf("\n--- Test: Server Lifecycle ---\n");

    // Test default config
    http_config_t config = http_server_default_config();
    TEST_ASSERT(config.port == 8080, "Default port is 8080");
    TEST_ASSERT(config.max_connections == 4, "Default max_connections is 4");
    TEST_ASSERT(config.timeout_ms == 5000, "Default timeout is 5000ms");

    // Test not running initially
    TEST_ASSERT(!http_server_is_running(), "Server not running initially");

    // Test init with ephemeral port
    http_config_t test_config = {
        .port = 0, // Ephemeral
        .max_connections = 2,
        .timeout_ms = 2000,
    };

    int result = http_server_init(&test_config);
    TEST_ASSERT(result == 0, "Server init succeeded");

    // Read the auth token generated during init
    result = read_auth_token();
    TEST_ASSERT(result == 0, "Auth token read from file");
    TEST_ASSERT(strlen(g_auth_token) > 0, "Auth token is non-empty");

    uint16_t port = http_server_get_port();
    TEST_ASSERT(port > 0, "Got ephemeral port");
    printf("    Using port: %d\n", port);

    // Test start
    result = http_server_start(true);
    TEST_ASSERT(result == 0, "Server start succeeded");
    TEST_ASSERT(http_server_is_running(), "Server is running");

    // Give server time to start
    apis_sleep_ms(100);

    // Run endpoint tests
    test_status_endpoint(port);
    test_auth(port);
    test_arm_disarm_endpoints(port);
    test_config_endpoints(port);
    test_manual_capture_state_machine();
    test_capture_endpoint(port);
    test_claim_endpoint(port);
    test_stream_endpoint(port);
    test_error_handling(port);

    // Test stop
    http_server_stop();
    TEST_ASSERT(!http_server_is_running(), "Server stopped");

    // Test cleanup
    http_server_cleanup();
}

// ============================================================================
// Main
// ============================================================================

int main(void) {
    // Initialize logging (suppress during tests)
    log_init(NULL, LOG_LEVEL_ERROR, false);

    // Initialize config manager (needed for arm/disarm and config endpoints)
    config_manager_init(true); // Use dev path
    config_manager_complete_setup(); // Mark setup done so 404 works (not redirect to /setup)
    deterrent_state_init("./data/apis/deterrent");
    vision_runtime_init();
    manual_capture_init();

    printf("=== HTTP Server Tests ===\n");

    test_server_lifecycle();

    printf("\n=== Results: %d passed, %d failed ===\n",
           tests_passed, tests_failed);

    config_manager_cleanup();
    deterrent_state_cleanup();
    vision_runtime_cleanup();
    manual_capture_cleanup();

    return tests_failed > 0 ? 1 : 0;
}
