-- Migration 0035: Force Row Level Security
-- SECURITY FIX (DL-H07): Tables had RLS enabled but not forced.
-- Without FORCE, the table owner (typically the connecting user) bypasses RLS policies.
-- ALTER TABLE ... FORCE ROW LEVEL SECURITY ensures RLS applies to ALL users including the owner.

ALTER TABLE users FORCE ROW LEVEL SECURITY;
ALTER TABLE sites FORCE ROW LEVEL SECURITY;
ALTER TABLE units FORCE ROW LEVEL SECURITY;
ALTER TABLE detections FORCE ROW LEVEL SECURITY;
ALTER TABLE clips FORCE ROW LEVEL SECURITY;
ALTER TABLE hives FORCE ROW LEVEL SECURITY;
ALTER TABLE queen_history FORCE ROW LEVEL SECURITY;
ALTER TABLE box_changes FORCE ROW LEVEL SECURITY;
ALTER TABLE inspections FORCE ROW LEVEL SECURITY;
ALTER TABLE inspection_frames FORCE ROW LEVEL SECURITY;
ALTER TABLE treatments FORCE ROW LEVEL SECURITY;
ALTER TABLE feedings FORCE ROW LEVEL SECURITY;
ALTER TABLE harvests FORCE ROW LEVEL SECURITY;
ALTER TABLE harvest_hives FORCE ROW LEVEL SECURITY;
ALTER TABLE equipment_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE insights FORCE ROW LEVEL SECURITY;
ALTER TABLE export_presets FORCE ROW LEVEL SECURITY;
ALTER TABLE milestone_photos FORCE ROW LEVEL SECURITY;
ALTER TABLE hive_losses FORCE ROW LEVEL SECURITY;
ALTER TABLE season_recaps FORCE ROW LEVEL SECURITY;
ALTER TABLE overwintering_records FORCE ROW LEVEL SECURITY;
ALTER TABLE custom_labels FORCE ROW LEVEL SECURITY;
ALTER TABLE reminders FORCE ROW LEVEL SECURITY;
ALTER TABLE invite_tokens FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE ROW LEVEL SECURITY;
ALTER TABLE task_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE hive_tasks FORCE ROW LEVEL SECURITY;
ALTER TABLE task_suggestions FORCE ROW LEVEL SECURITY;
ALTER TABLE hive_activity_log FORCE ROW LEVEL SECURITY;
